import os
cwd = os.getcwd()
fid=open('start.desktop','w')
fid.write('#!/usr/bin/env xdg-open\n')
fid.write('[Desktop Entry]\n')
fid.write('Version=1.0\n')
fid.write('Type=Application\n')
fid.write('Terminal=true\n')
fid.write('Icon[en_US]=python3\n')
fid.write('Name[en_US]=Insight deep learning GUI\n')
path=os.path.join(cwd, 'gui.py')
fid.write('Exec=bash -c "cd %s && /usr/bin/python3 %s"\n'%(cwd,path))
fid.write('Name=Insight deep learning GUI\n')
fid.write('Icon=python3\n')
fid.close()
os.system('chmod +x start.desktop')
